// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func OrganizationForm() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"modal-backdrop\" data-on:click__outside=\"this.parentElement.innerHTML=''\"><div class=\"modal\" data-on:click__stop=\"\"><div class=\"modal-header\"><h2>New Organization</h2><button class=\"close-btn\" data-on:click=\"this.closest('#org-form-modal').innerHTML=''\">&times;</button></div><form class=\"entity-form\" data-signals=\"{_submitting: false}\" data-on:submit__prevent=\"@post('/api/organizations', {contentType: 'form'})\" data-indicator:_submitting><div class=\"form-group\"><label for=\"name\">Organization Name *</label> <input type=\"text\" name=\"name\" id=\"name\" required placeholder=\"e.g., Task Force Alpha\" maxlength=\"255\"> <small>Unique identifier for your organization</small></div><div class=\"form-group\"><label for=\"org_type\">Organization Type *</label> <select name=\"org_type\" id=\"org_type\" required><option value=\"\">Select Type</option> <option value=\"military\">Military</option> <option value=\"civilian\">Civilian</option> <option value=\"commercial\">Commercial</option> <option value=\"ngo\">NGO (Non-Governmental Organization)</option></select> <small>Defines the organizational classification</small></div><div class=\"form-group\"><label for=\"description\">Description (Optional)</label> <textarea name=\"description\" id=\"description\" rows=\"3\" placeholder=\"Brief description of the organization's purpose or mission\" maxlength=\"500\"></textarea> <small>Maximum 500 characters</small></div><div class=\"form-actions\"><button type=\"submit\" class=\"action-btn primary\" data-attr:disabled=\"$_submitting\"><span data-show=\"!$_submitting\">Create Organization</span> <span data-show=\"$_submitting\">Creating...</span></button> <button type=\"button\" class=\"action-btn\" data-on:click=\"this.closest('#org-form-modal').innerHTML=''\">Cancel</button></div></form></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
